# vim: ft=dockerfile:
# Dockerfile to build aria2 iOS binary using osxcross
#
# $ sudo docker build -t aria2-ios - < Dockerfile.ios
#
# After successful build, iOS binary is located under
# /root/build/aria2.  You can copy the binary using docker cp.  For
# example, to copy aria2c binary to host file system location
# /path/to/dest, do this:
#
# $ sudo docker run --rm -it -v /path/to/dest:/out aria2-ios cp /root/build/aria2/src/aria2c /out

FROM ubuntu:22.04
MAINTAINER Tatsuhiro Tsujikawa

WORKDIR /root
RUN apt-get update && \
    apt-get install -y  --no-install-recommends \
      unzip bzip2 make binutils autoconf automake autotools-dev autopoint \
      libtool pkg-config git curl ca-certificates \
      python3-docutils clang lld cmake libxml2-dev libssl-dev patch && \
    rm -rf /var/cache/apt/*

# Set up iOS toolchain using osxcross
ENV IOS_SDK_VERSION=16.4
ENV HOST=arm64-apple-darwin
ENV PREFIX=/root/usr/local
ENV OSXCROSS_SDK_VERSION=13.3

# Install osxcross for iOS cross-compilation
WORKDIR /root
RUN git clone https://github.com/tpoechtrager/osxcross.git && \
    cd osxcross && \
    UNATTENDED=1 ./tools/get_dependencies.sh && \
    cd tarballs && \
    curl -L -o MacOSX${OSXCROSS_SDK_VERSION}.sdk.tar.xz \
      "https://github.com/joseluisq/macosx-sdks/releases/download/${OSXCROSS_SDK_VERSION}/MacOSX${OSXCROSS_SDK_VERSION}.sdk.tar.xz" && \
    cd .. && \
    UNATTENDED=1 SDK_VERSION=${OSXCROSS_SDK_VERSION} OSX_VERSION_MIN=11.0 ./build.sh

ENV PATH="/root/osxcross/target/bin:${PATH}"
ENV OSXCROSS_TARGET_DIR=/root/osxcross/target
ENV OSXCROSS_SDK=/root/osxcross/target/SDK/MacOSX${OSXCROSS_SDK_VERSION}.sdk

# Set up compiler variables for iOS
ENV CC=arm64-apple-darwin22-clang
ENV CXX=arm64-apple-darwin22-clang++
ENV AR=arm64-apple-darwin22-ar
ENV RANLIB=arm64-apple-darwin22-ranlib
ENV STRIP=arm64-apple-darwin22-strip
ENV LD=arm64-apple-darwin22-ld

# aria2 version
ARG ARIA2_VERSION=master

# Library versions
ENV OPENSSL_VERSION=1.1.1w
ENV OPENSSL_ARCHIVE=openssl-$OPENSSL_VERSION.tar.gz
ENV OPENSSL_URI=https://www.openssl.org/source/$OPENSSL_ARCHIVE

ENV LIBEXPAT_VERSION=2.5.0
ENV LIBEXPAT_ARCHIVE=expat-$LIBEXPAT_VERSION.tar.bz2
ENV LIBEXPAT_URI=https://github.com/libexpat/libexpat/releases/download/R_2_5_0/$LIBEXPAT_ARCHIVE

ENV ZLIB_VERSION=1.3.1
ENV ZLIB_ARCHIVE=zlib-$ZLIB_VERSION.tar.gz
ENV ZLIB_URI=https://github.com/madler/zlib/releases/download/v1.3.1/$ZLIB_ARCHIVE

ENV CARES_VERSION=1.21.0
ENV CARES_ARCHIVE=c-ares-$CARES_VERSION.tar.gz
ENV CARES_URI=https://github.com/c-ares/c-ares/releases/download/cares-1_21_0/$CARES_ARCHIVE

ENV LIBSSH2_VERSION=1.11.0
ENV LIBSSH2_ARCHIVE=libssh2-$LIBSSH2_VERSION.tar.bz2
ENV LIBSSH2_URI=https://libssh2.org/download/$LIBSSH2_ARCHIVE

# iOS specific flags
ENV IOS_FLAGS="-arch arm64 -miphoneos-version-min=12.0 -isysroot $OSXCROSS_SDK"
ENV CFLAGS="$IOS_FLAGS -Os -g"
ENV CXXFLAGS="$IOS_FLAGS -Os -g -stdlib=libc++"
ENV LDFLAGS="$IOS_FLAGS -L$PREFIX/lib"

# Build OpenSSL
WORKDIR /root/build
RUN curl -L -O $OPENSSL_URI && tar xf $OPENSSL_ARCHIVE && rm $OPENSSL_ARCHIVE

WORKDIR /root/build/openssl-$OPENSSL_VERSION
RUN ./Configure no-shared --prefix=$PREFIX ios64-cross && \
    make -j$(nproc) && make install_sw

# Build libexpat
WORKDIR /root/build
RUN curl -L -O $LIBEXPAT_URI && tar xf $LIBEXPAT_ARCHIVE && rm $LIBEXPAT_ARCHIVE

WORKDIR /root/build/expat-$LIBEXPAT_VERSION
RUN ./configure \
      --host=$HOST \
      --prefix=$PREFIX \
      --disable-shared && \
    make -j$(nproc) install

# Build zlib
WORKDIR /root/build
RUN curl -L -O $ZLIB_URI && tar xf $ZLIB_ARCHIVE && rm $ZLIB_ARCHIVE

WORKDIR /root/build/zlib-$ZLIB_VERSION
RUN ./configure \
      --prefix=$PREFIX \
      --static && \
    make -j$(nproc) install

# Build c-ares
WORKDIR /root/build
RUN curl -L -O $CARES_URI && tar xf $CARES_ARCHIVE && rm $CARES_ARCHIVE

WORKDIR /root/build/c-ares-$CARES_VERSION
RUN ./configure \
      --host=$HOST \
      --prefix=$PREFIX \
      --disable-shared && \
    make -j$(nproc) install

# Build libssh2
WORKDIR /root/build
RUN curl -L -O $LIBSSH2_URI && tar xf $LIBSSH2_ARCHIVE && rm $LIBSSH2_ARCHIVE

WORKDIR /root/build/libssh2-$LIBSSH2_VERSION
RUN ./configure \
      --host=$HOST \
      --prefix=$PREFIX \
      --disable-shared && \
    make -j$(nproc) install

# Build aria2
WORKDIR /root/build
RUN git clone -b $ARIA2_VERSION --depth 1 https://github.com/aria2/aria2

WORKDIR /root/build/aria2
RUN autoreconf -i && \
    ./configure \
      --host=$HOST \
      --disable-nls \
      --without-gnutls \
      --with-openssl \
      --without-sqlite3 \
      --without-libxml2 \
      --with-libexpat \
      --with-libcares \
      --with-libz \
      --with-libssh2 \
      CXXFLAGS="$CXXFLAGS" \
      CFLAGS="$CFLAGS" \
      LDFLAGS="$LDFLAGS" \
      PKG_CONFIG_LIBDIR="$PREFIX/lib/pkgconfig" && \
    make -j$(nproc) && \
    $STRIP src/aria2c
